### ISSUE TITLE
[Shoelace] - Missing Component List

### ISSUE THREAD

**Issue by AngelMunoz** [AngelMunoz/SutilWebComponents#2]
Since Shoelace is the primary library I'm working for I thought it's best to keep a track of the current items I'm done with and the ones that are missing

- [x] Alert
- [x] Avatar
- [x] Badge
- [x] Button
- [x] Button Group
- [x] Card
- [x] Checkbox
- [x] Color Picker
- [x] Details
- [x] Dialog
- [x] Drawer
- [x] Dropdown
- [x] Form
- [x] Icon
- [x] Icon Button
- [x] Image Comparer
- [x] Input
- [x] Menu
- [x] Menu Divider
- [x] Menu Item
- [x] Menu Label
- [x] Progress Bar
- [x] Progress Ring
- [x] Radio
- [x] Radio Group
- [x] Range
- [x] Rating
- [x] Select
- [x] Skeleton
- [x] Spinner
- [x] Switch
- [x] Tab Group
- [x] Tab
- [x] Tab Panel
- [x] Tag
- [x] Textarea
- [x] Tooltip
- [x] Animation
- [ ] Format Bytes
- [ ] Format Date
- [ ] Format Number
- [ ] Include
- [ ] QR Code
- [ ] Relative Time
- [ ] Resize Observer
- [ ] Responsive Media

**Comment by AngelMunoz** [comment]
So... I just found out that there is 
https://github.com/shoelace-style/react-generator

this means that we should be able to generate these mild wrappers programatically I'll stop what I'm doing and I'll start evaluating if a custom dotnet tool can help us generate what we need in this case

**Comment by AngelMunoz** [comment]
Regarding Shoelace the work continued here https://github.com/AngelMunoz/Shoelace.Generator and it's basically done and working I'll be adding the docs website for Sutil.Shoelace in the near future but a nuget package has been released in the meantime 
https://www.nuget.org/packages/Sutil.Shoelace
The version of that nuget will be tied and generated from the Shoelace version it was built agains 
@davedawkins you might want to take a look

**Comment by davedawkins** [comment]
Nice work Angel!
